apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-jenkins-deployment
  labels:
    app: k8s-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-jenkins
  template:
    metadata:
      labels:
        app: k8s-jenkins
    spec:
      serviceAccountName: default
      containers:
      - name: jenkins
        image: jenkins/jenkins
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
          - containerPort: 50000
        volumeMounts:
          - name: jenkins-persistent-storage
            mountPath: /var/lib/jenkins
     volumes:
       - name: jenkins-persistent-storage
         persistentVolumeClaim:
           claimName: jenkins-pv-claim
